---
brew_packages:
  - git
  - docker
  - docker-compose
  - mas
  - dockutil
  - grep
  - tig
  - stow
  - fzf
  - htop
  - node
  - python
  - ripgrep
  - neovim
  - eza
  - go
  - lazydocker
  - htop
  - jq
  - nmap
  - ruby
  - tmux
  - wget
  - zsh

cask_packages:
  - 1password
  - google-chrome
  - slack
  - rambox
  - postman
  - brave-browser
  - vial
  - raycast
  - ghostty
  - shureplus-motiv

dockitems_to_remove:
  - Safari
  - Erinnerungen
  - Fotos
  - Nachrichten
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - Systemeinstellungen

macos_dock_autohide: true
macos_dock_icon_size: 36
macos_dock_orientation: bottom
macos_dock_show_recents: false

dockitems_to_persist:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Brave Browser
    path: "/Applications/Brave Browser.app"
    pos: 2
  - name: Kalender
    path: /Applications/Calendar.app
    pos: 3
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 4
  - name: Ghostty
    path: /Applications/Ghostty.app
    pos: 5
  - name: 1Password
    path: /Applications/1Password.app
    pos: 6
  - name: Rambox
    path: /Applications/Rambox.app
    pos: 7
  - name: Mail
    path: /Applications/Mail.app
    pos: 8
  - name: Notizen
    path: /Applications/Notes.app
    pos: 9
