---
brew_taps:
  - homebrew/cask-fonts

brew_packages:
  - ansible
  - git
  - docker
  - docker-compose
  - grep
  - tig
  - stow
  - fzf
  - htop
  - node
  - python
  - ripgrep
  - neovim
  - exa
  - go
  - htop
  - jq
  - nmap
  - ruby
  - tmux
  - wget
  - zsh

cask_packages:
  - 1password
  - docker
  - font-hack-nerd-font
  - google-chrome
  - iterm2
  - slack
  - rambox
  - postman
  - brave-browser
  - vial
  - spectacle
  - shureplus-motiv

mas_packages:
  - 937984704  # Amphetamine

npm_packages:
  - yarn
  - eslint
  - typescript-language-server
  - typescript
  - prettier

pip_packages:
  - docker
