---
- name: Set up local workstation
  hosts: local

  vars_files: ["config.defaults.yml", "vars.yml"]

  pre_tasks:
    - name: "Include config.yml overrides"
      include_vars: "{{ item }}"
      with_fileglob: "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: ssh
      tags: ["ssh"]

    - role: git
      tags: ["git"]

    - role: zsh
      tags: ["zsh"]

    - role: dotfiles
      tags: ["dotfiles"]

    - role: docker
      tags: ["docker"]

    - role: macos
      tags: ["macos"]
      when: ansible_distribution == 'MacOSX'

    - role: geerlingguy.mac.homebrew
      tags: ["brew"]
      when: ansible_distribution == 'MacOSX'

    - role: brew
      tags: ["brew"]
      when: ansible_distribution == 'MacOSX'

    - role: mas
      tags: ["mas"]
      when: ansible_distribution == 'MacOSX'

    - role: macdock
      tags: ["macdock"]
      when: ansible_distribution == 'MacOSX'
