---
- name: Check if npm package is already installed
  command: npm list -g --depth=0 {{ item }}
  register: npm_check
  ignore_errors: true
  changed_when: false
  loop: "{{ npm_packages }}"
  loop_control:
    loop_var: item

- name: Install npm packages if not already installed
  block:
   - name: Install npm package globally
     npm:
      name: "{{ item }}"
      global: true
  when: npm_check.results[loop.index0].rc != 0
  loop: "{{ npm_packages }}"
  loop_control:
    loop_var: item

