---
- name: "Include main vars"
  ansible.builtin.include_vars:
    file: vars.yml

- name: "Cloning .dotfiles"
  ansible.builtin.git:
    repo: 'git@github.com:Beargruug/.dotfiles.git'
    key_file: "{{ ssh_key_filename }}"
    dest: "~/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - dotfiles

- name: "Stow dotfiles"
  shell: cd ~/.dotfiles && ./macos && ./install
  tags:
    - install
    - dotfiles
    - stow
