---
- name: "Include main vars"
  ansible.builtin.include_vars:
    file: vars.yml

- name: "Cloning .dotfiles"
  ansible.builtin.git:
    repo: 'https://github.com/Beargruug/.dotfiles.git'
    dest: "~/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    key_file: "{{ ssh_key }}"
    version: main
  tags:
    - dotfiles

- name: "Permissions for dotfiles"
  shell: cd ~/.dotfiles && sudo chmod 755 ./macos && chmod 755./install
  tags:
    - dotfiles
    - stow

- name: "Add personal folder to dotfiles"
  shell: cd ~/.dotfiles && mkdir personal
  tags:
    - dotfiles
    - stow

- name: "Stow dotfiles"
  shell: cd ~/.dotfiles && ./macos
  tags:
    - dotfiles
    - stow
