---
- name: "[ macOS] Disable press-and-hold for keys in favor of key repeat"
  tags: macos
  osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
    state: present

- name: "[ macOS] Set a blazingly fast keyboard repeat rate"
  tags: macos
  osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: integer
    value: 2
    state: present

- name: "[ macOS] Set a short keyboard repeat rate delay"
  tags: macos
  osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: integer
    value: 35
    state: present

- name: "[ macOS] Increase speed of trackpad cursor movement"
  tags: macos
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.trackpad.scaling
    type: float
    value: 4
    state: present
