---
- name: "[ homebrew] Install Homebrew formulae"
  tags:
    - homebrew
  homebrew:
    name: "{{ item }}"
  loop: "{{ brew_packages }}"

- name: "[ homebrew] Install Homebrew casks"
  tags:
    - homebrew
    - caskbrew
  homebrew_cask:
    name: "{{ item }}"
  loop: "{{ cask_packages }}"
